import pytest
import pandas as pd
import numpy as np
from pathlib import Path



@pytest.fixture(scope="session")
def sample_complaints_df():
    """DataFrame de quejas de ejemplo para tests"""
    return pd.DataFrame({
        'Número del caso': [26013136993422,
                            26013036986963,
                            26013136992033,
                            26013136992046,
                            26013036984119,
                            26020136994915,
                            26013136993304,
                            26013136992626,
                            26012936973901,
                            26013136993966],
        'Prestación': [np.nan,
                       np.nan,
                       np.nan,
                       'IPS',
                       np.nan,
                       np.nan,
                       np.nan,
                       np.nan,
                       np.nan,
                       np.nan],
        'Filtro 3': ['TELEVENTAS BANCA',
                     np.nan,
                     'COLSUBSIDIO',
                     'SALUD SURA SAO PAULO',
                     'MEDELLIN-4292',
                     np.nan,
                     np.nan,
                     np.nan,
                     'LINEA SALUD',
                     np.nan],
        'Filtro 4': [np.nan,
                     np.nan,
                     'CONSULTA CON ESPECIALISTA',
                     'CONSULTA CON MEDICO GENERAL O ESPECIALISTA',
                     np.nan,
                     np.nan,
                     np.nan,
                     np.nan,
                     np.nan,
                     np.nan],
        'Proceso': ['ASESORIA Y VENTA',
                    'ASESORIA Y VENTA',
                    'ASISTENCIA SALUD',
                    'ASISTENCIA SALUD',
                    'EVALUACION',
                    'EXPEDICION',
                    'RECAUDOS',
                    'RECLAMACIONES SALUD',
                    'RELACIONAMIENTO Y SERVICIO AL CLIENTE',
                    'TRANSFORMACION DIGITAL'],
        'Causa': ['INADECUADA ATENCION DEL ASESOR', 
                  'DESCONTENTO CON EL PRODUCTO', 
                  'INADECUADA ATENCION DEL PROVEEDOR/PRESTADOR',
                  'INADECUADA ATENCION DEL EMPLEADO SURA',
                  'NO ACEPTACION DEL BIEN O PERSONA ASEGURADA',
                  'DEMORA EN LA CANCELACION',
                  'DOBLE COBRO',
                  'PROBLEMAS CON AUTORIZACIONES DE SALUD',
                  'INCONFORMIDAD EN LA COMUNICACION CON LA LINEA DE ATENCION',
                  'INCONVENIENTES CLAVE SURA.COM'],
        'Descripción': [
            'inconforme con la asesora ya que dice que siempre que la llama lo que le responde es que en el momento no la puede atender.',
            'anexo carta queja',
            'el profesional estaba viendo porno el trato regular e impersonal',
            'presento queja sobre la mala atención del personal de caja, son groseras al atender el público, irrespetuosas',
            'solicita información sobre el motivo por el cual no le permiten ingresar o afiliarse a la póliza de salud, indica que se encuentra bloqueada sin una explicación clara.',
            'solicitó el retiro de uno de los asegurados y después de varios días aún no se ha realizado.',
            'inconformidad por un doble débito automático en el mes de diciembre, porque el cobro que se le ha hecho siempre es mensual.',
            'se comunica paciente solicitando nuevamente el cambio de prestador.',
            'servicio de atención telefónica muy demorado, se demoran demasiado en responder las llamadas.',
            'no ha podido ingresar a la sucursal virtual desde la página web; el sistema solicita cambio de clave pero no permite continuar.'
        ],
        'Fecha de apertura': pd.to_datetime(['2025-01-01',
                                             '2025-01-02',
                                             '2025-01-03',
                                             '2025-01-04',
                                             '2025-01-05',
                                             '2025-01-06',
                                             '2025-01-07',
                                             '2025-01-08',
                                             '2025-01-09',
                                             '2025-01-10'])
    })