from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]
INPUT_DIR = BASE_DIR / 'Input'
INPUT_THRESHOLDS_DIR = INPUT_DIR / 'Thresholds'
MODEL_PROCESS_DIR = BASE_DIR / 'Models' / 'Process'
MODEL_CAUSES_DIR = BASE_DIR / 'Models' / 'Causes'
DICT_SERVICES_DIR = INPUT_DIR / 'Filter4'
OUTPUT_DIR = BASE_DIR / 'Output'
OUTPUT_ALERTS_DIR = OUTPUT_DIR / 'alerts'
OUTPUT_MONITORING_DIR = OUTPUT_DIR / 'monitoring'



# PROCESS_EXAMPLES = {

#     'AYV': [
#         'exige que le cambien el asesor por que no le contesta ni se comunica con él.',
#         'mi queja es sobre uno de los asesores del plan complementario debido a que nunca responde los mensajes y por telefono su actitud no es nada amable, cada vez que intento comunicarme debe ser muchas veces sino no responde.',
#         'cancelacion de mi contrato de salud para todos, ya que fue expedido sin consentimiento, donde en ningun momento firme para la respectiva expedición. en algun momento si le pedi informacion a la asesora pero solo para conocer el plan y de un momento a otro me comenzaron a cobrar el servicio.',
#         'inconformidad frente a la atencion brindada por parte del asesor comercial quien me vendio una poliza de salud plan salud para todos en el mes junio, le he estado escribiendo al whatsapp y me deja en visto no me ha dado ninguna respuesta al respecto.',
#         'a la fecha no he solicitado, ni aprobado la adquisición o compra de un seguro.',
#         'inconformidad con póliza donde omitieron información y la cual no me ha servido para nada cuando la fui a utilizar.',
#         'inconformidad y descontento con el producto, no esta conforme ya que le cambiaron las condiciones sin informarle y la estan perjudicando.',
#         'deseo cancelar el seguro odontologico quer adquiri por haberme engañado al momento de la venta, diciendome que tenía coberturas que hoy me entero que no cubre; los agentes con tal de vender dicen cualquier cosa, lo que me parece falto de ética. No estoy conforme con el servicio adquirido.',
#         'descontento con el plan de salud que logré tomar con sura',
#         'en ningún momento he pedido esta poliza para mi familia. necesito que esto sea cancelado.',
#         'nos atienden como cualquier eps',
#         'necesito cancelar una poliza que firmé sin saber ya que nunca me informaron qué era, yo creí que firmaba documentos por la apertura de la cuenta.',
#         'desea cambiar de asesor',
#         'cambiar de asesor ya que no le ha prestado un buen servicio.',
#         'solicito por favor cambio de asesor ya que me lo cambiaron sin mi consentimiento.',
#         'información falsa al momento de la vinculación del producto',
#         'queja contra el asesor que le vendió el seguro.',
#         'cambio de asesor por negligente',
#         'no le cubre lo que le ofrecieron. Venta con engaño.',
#         'información errada en venta de poliza',
#         'asesora activa póliza de salud sin autorización.',
#         'al momento de adquirir la poliza el asesor le dio una información incorrecta sobre los beneficios de la póliza al momento de querer usarlos le informaron que no era correcto lo que le habían informado, está demasiado inconforme por mala venta del asesor.',
#         'mi póliza no tiene coberturas en la ciudad',
#         'nos quitaron la especialidad de fisiatria, lo que me parece injusto.',
#         'estoy considerando pasarme de póliza junto con mi grupo familiar si no nos dan la libertad de elegir nuestros prestadores.',
#         'considera le vendieron con mentiras',
#         'solicitando explicaciones y motivos de cambios en mi plan de poliza sin yo solicitarlo.',
#         'asegurado no esta de acuerdo con la tarifa de sura, no acepta el nuevo valor.',
#         'después de entregar una renovación me cambian el valor de la prima mensual',
#         'no es nada grato que le cambien a uno los beneficios y mas sin previo aviso, se supone que uno contrata unas coberturas y sin mas las desmejoran.',
#         'en los dos ultimos años hemos recibido unos incrementos desmedidos sin tener una explicación justificable.',
#         'no me ha ido muy bien con el plan no me ha funcionado cuando lo necesito.',
#         'le vendieron la poliza de manera engañosa, le ofrecieron coberturas y servicios que la póliza no tenia realmente',
#         'por medio del presente adjunto derecho de petición',
#         'anexo carta queja'
#         ],


#     'ASISTENCIA': [
#         'solicitando por favor le ayuden con la asignacion de cita y/o un numero telefónico donde le contesten ya que lleva varios dias llamando buscó también en internet y en ninguno de los números contestan',
#         'inconformidad por el tiempo de duración de las consultas. indica que es muy complicado encontrar disponibilidad como para que el tiempo estipulado sea tan corto.',
#         'traje a mi hija a sura porque tenia un dolor en el pecho y dificultad para respirar. hoy vuelvo con ella porque su condición ha empeorado. no la envían con especialista ni hacen examenes.',
#         'tenía una muestra de laboratorios a domicilio, tuve que recolectar orina durante 24 horas, la funcionaria que toma los exámenes me indica que va a desechar la muestra de 24 horas porque se lleva una muestra que yo tambien entregue en un recolector de panel de orina, el medico que me la solicitó me dice que no es correcto la forma en que se entregó el examen y que no le sirve.',
#         'usuaria requiere ayuda para la entrega de resultados dado que presencial no se los entregan.',
#         'no tuve ninguna orientación en la recepción de piso. El personal de recepción no me indicó en ningún momento lo que debía hacer y estaban solo revisando el celular',
#         'las cajeras no tienen devuelta para uno poder pagar la terapia.',
#         'necesito una cita virtual y es imposible! nunca hay disponible',
#         'requiero adelanto de la cita',
#         'he esperado 2 meses una cita. requiero la cita pronto.',
#         'poca disponibilidad al tratar de agendar cita de medicina general.',
#         'no le prestaron el servicio de medicina interna, por falta de convenio.',
#         'Incodol no le quiere dar acceso directo para urología, indica que no tiene convenio.',
#         'le indican que no cuenta con el seguro y le niegan la consulta con el especialista.',
#         'se demoró un servicio de urgencia mas de 3 horas y luego de ese tiempo me envían un mensaje cancelando el servicio',
#         'me pusieron una inyeccion y me quedo un morado enorme, la zona esta dura y adolorida.',
#         'diagnóstico impreciso que me pone en riesgo vital',
#         'las dos ultimas ocasiones que me han tomado muestras de sangre me han dejado hematomas.',
#         'la persona que lo hizo no tuvo la suficuente habilidad para hacerme la punción lo cual me parecio demaciado dolorosa y le ocaciono una flebitis en el brazo',
#         'no me llego la incapacidad de cita virtual del 07 de febrero.',
#         'la doctora que me diagnosticó no tiene tacto con los pacientes. da miedo preguntarle algo',
#         'queja por atención recibida en el servicio de urgencias del hospital.',
#         'tuvimos ecografia con el dr. alvaro cano por el embarazo de mi esposa. durante todo el tiempo se noto perdido, no sabia manejar la maquina, hacia afirmaciones alarmistas y se retractaba. nos genero ansiedad y no queremos que le pase a otros',
#         'no hay aire en la sala de terapias y la temperatura de calor es muy fuerte.',
#         'aseo general del lugar sura industriales, las escalas desde el garaje sucias, el inodoro la tasa amarilla se ve horrible',
#         'sala sin suficientes asientos, las personas paradas incluyendo niños con padres y personas de la 3 edad',
#         'el servicio prestado no tiene la calidad suficiente, no esta conforme con servicio brindado por el prestador.',
#         'un examen mal hecho, estoy inconforme',
#         'trata mal a los pacientes y lo regaña a uno todo el tiempo.',
#         'el frio en odontologia hace la experiencia menos agradable.',
#         'no estamos conformes con la atención recibida por parte de la ginecologa , falta de profesionalismo y manejo humano',
#         'usuaria solicita que le corrijan la incapacidad, ya que debio ser por prorroga y se la transcribieron como inicial',
#         'la locación no es la adecuada para personas en embarazo, hace mucho calor y no hay aire acondicionado, las sillas muy incomodas para estar tanto tiempo sentados.',
#         'tengo agendada una cita para vacunación hace mas de 1 mes, al llegar a la sede me dicen que no tienen la vacuna.',
#         'vine por una vacuna y el tiempo de espera fue de 45 minutos',
#         'el servicio de urgencias es muy lento.',
#         'pedí cita virtual y no se respetan los horarios.',
#         'pedí una cita virtual a las 8:50. Son las 9:15 y nadie se a contactado conmigo,',
#         'demasiada demora, llevo para una urgencia de otitis mas de hora y media y nada',
#         'los tiempos de espera en cita con internista son muy largos, falta oportunidad en la hora de la cita',
#         'reagendamiento de citas sin consultarle al usuario',
#         'inconformidad porque le cancelaron la cita.',
#         'preocupacion con las cancelaciones de las citas medicas y de examenes.',
#         'inconforme porque le estan cobrando cuota moderadora en los medicamentos.',
#         'me cobraron una cuota moderadora, cuando mi plan dice que no deben hacerme cobros',
#         'fui a cita médica y en la ips me dicen que no aparezco en el plan.',
#         'nunca le llego el medicamento pero ya registra que se lo entregaron',
#         'mal servicio que prestan a la hora de realizar la entrega de medicamentos',
#         'el medicamento no llegó.',
#         'sinconforme con el domicilio de los medicamentos ya que indica que llegaron en muy malas condiciones e informa que da mucho que pensar porque parecen cajas reutilizadas.',
#         'solamente le hicieron entrega de cuatro pastillas del medicamento y la formula indica que es por 60, solicita que se le hagan la entrega de la cantidad faltante.',
#         'hice la peticion para que me enviaran a domicilio los medicamentos, a la fecha no han llegado y estos medicamentos son de uso diario por lo que les pido el favor de enviarlos lo antes posible',
#         'fui reclamar los medicamentos formulados pero me dice que estan agotados.',
#         'tenía programada la entrega de un medicamento y a la fecha no ha llegado. al ingresar a la página por medicamentos no tengo nada pendiente por reclamar.',
#         'le realizaron examen y no registra resultado',
#         'demora en la entrega de resultados',
#         'el sistema no deja ver o descargar los resultados de exámenes de laboratorio',
#         'le realizaron el estudio genetico a mi bebé y a la fecha aun sigue apareciendo en proceso. El tiempo ya pasó.',
#         'me realizaron el examen y el resultado no me lo han enviado.',
#         'ayuda con la asignacion de la cita.',
#         'he intentado solicitar cita para toma de muestras de laboratorio clínico, pero ha sido imposible.',
#         'solicito cita de ortopedia. Los del directorio dicen no tener convenio.',
#         'llevo pidiendo una cita odontología que requiero y no me la han dado.',
#         'ha sido imposible acceder a una cita.',
#         'estoy tratando de conseguir una cita y nunca tienen agenda.',
#         'mucha dificultad para la toma de muestras.',
#         'no me atendieron para examenes de laboratorio',
#         'usuario indica que no le atendieron urgencias en la clinica farallones.',
#         'mala evaluación del optómetra y me receta unos lentes que son con una formula mas alta de lo necesitado.',
#         'el baño de hombres en la piscina está malo hace mas de 6 meses, toca vestirse parado.',
#         'creo que en lugares como este, atención a salud humana, con tanta gente en riesgo, no deberian permitirse el ingreso de mascotas salvo en circunstancias especiales de la ley',
#         'en la zona de la piscina hay un ruido constante que perturba el tratamiento de la hidroterapia y la concentración.',
#         'la atención es muy demorada, malas caras por parte de las funcionarias del laboratorio, desde que ingresa a la sede la atención y el ambiente es super pesado no es para nada agradable',
#         'inconformidad con el tiempo de atención de médico domiciliario de mi poliza. se prometió un tiempo máximo de espera de 3 horas. el servicio realmente llego 5 horas después.',
#         'queja por mala atención y mal servicio en la sede.',
#         'llego a urgencias con mi niña de 5 anos. llevo una hora esperando a que la pase el doctor lo que me parece absurdo pagando una poliza tan costosa.',
#         'la cita aparece reprogramada para el 10 de noviembre sin ninguna explicación',
#         'tenía cita para mañana, ahora me dicen que queda cancelada que pida otra. voy a pedirla y estan para 6 meses.',
#         'dicen que no tengo seguro de salud cuando lo he venido pagando a tiempo mes a mes.',
#         'dice no estar de acuerdo con las fechas de entrega del medicamento, por que la entrega debe de ser para cada 28 dias que es el tiempo del tratamiento, y no cada mes.',
#         'solicito resultados de laboratorio, son urgentes',
#         'usuaria solicita resultado de citologia vaginal tumoral, dice que no ha podido obtener el resultado.',
#         'demoradísimo el turnero para entregar un simple resultado de examen esperamos mas de 30 minutos.'
#         ],


#     'EXPEDICION': [
#         'solicitando la activación a la poliza, enviaron correo para el proceso de migración de la usuaria y no ha sido posible.',
#         'necesito cancelar el plan complementario.',
#         'aclaración con respecto a mi poliza de salud la cual me fue cancelada sin avisarme.',
#         'Aparezco desafiliada solicito aclarar ya que no he solicitado desafiliación',
#         'al momento de solicitar una certificación de antigüedad y preexistencias con ustedes, no sale este comentario. por favor actualizar la información y me emiten este documento.',
#         'recibió un correo electrónico donde le informaban la cancelación de su poliza y que se la modificaban para mayor información que se debia contactar al #888, por tal motivo la asegurada se encuentra muy molesta, ya que nunca le consultaron tal suceso.',
#         'cobro a cliente que no tiene seguro',
#         'cliente se comunica porque le esta haciendo cobros de su cuenta y no tiene productos con nosotros.',
#         'queja por cobros realizado y no tiene productos',
#         'solicita el envío de la facturación de la poliza',
#         'favor descongelar poliza',
#         'se solicita actualización urgente del documento de identidad de la menor elena vasquez garcia.',
#         'deseo cancelar mi poliza de salud lo antes posible',
#         'solicitud reiterada de cancelación poliza salud',
#         'se requiere que se corrija esta preexistencia en el certificado',
#         'he solicitado en varias veces el retiro de salud mas desde hace 7 meses y me siguen debitando dinero, no estoy interesado en sus servicios.',
#         'validar el retiro de la poliza, hasta el momento no he obtenido ninguna repuesta el retiro',
#         'solicité actualización de documento, me aparece aprobado y a las 3:20 del mismo día me llega otro correo notificándome que el documento esta desactualizado.',
#         'solicito nuevamente excluir las preexistencias anotadas en mi carátula de mi plan complementario.',
#         'reportar que mi hijo no aparece en el sistema del plan salud.',
#         'se hizo un cambio de grupo familiar y ahora mi hijo no aparece activo.',
#         'solicitud de reactivación seguro poliza de salud.',
#         'indica que le cancelaron la poliza, necesita que se lo activen.',
#         'corrijan mi correo electronico.',
#         'el carné tiene errores, el nombre de ella sale con fecha de nacimiento y documento de identidad de su esposo.',
#         'por favor solicito me devuelvan a mi plan complementario ya que en ningun momento he autorizado el cambo de plan.',
#         'solicité el certificado para la declaración de renta y me llego incompleto.',
#         'van 3 veces que me niegan el servicio porque para sura fallecí, mi asesor soluciona el tema, pero busco una solución definitiva.',
#         'requiere carné de póliza físico',
#         'solicitando carné virtual',
#         'necesito que sea rectificada la antigüedad de mi grupo familiar.',
#         'me colaboran por favor con el certificado de antiguedad y preexistencias',
#         'solicito certicado de fecha de ingreso de sura al plan complementario. preexistencia de todo mi grupo familiar',
#         'registros no soportados en mi poliza y utilizaciones.',
#         'requiero se me haga entrega de mi tiempo de antigüedad en la prepagada, hice la solicitud en la plataforma no he tenido respuesta por favor',
#         'solicito colaboracion con paz y salvo de la póliza de de familia que tenía con ustedes.',
#         'solicité un certificado para declaración de renta y aún no me lo han enviado.',
#         'necesito la historia clínica, no me han dado respuesta. la necesito urgente',
#         'recibí por fin el certificado que pedí y nuevamente llego mal.',
#         'solicito revisión de emisión de certificado ya que al generarlo por la plataforma de sura figura mi nombre dos veces y no el de mi hija beneficiaria.',
#         'se solicita corrección de fecha de nacimiento.',
#         'mi poliza de salud fue cancelada sin motivo.',
#         'no le han hecho la correcion de datos y no a podido utilizar sus servicios.'
#     ],


#     'RECAUDO': [
#         'voy a pagar el mes de marzo de sura poliza y no permite porque sale febrero pendiente de pago y este pago de febrero ya se realizó.',
#         'estoy tratando de realizar el pago de salud para todos mi segunda cuota y dice que no registra ningún pago pendiente',
#         'necesita que por favor se haga el débito automático.',
#         'no deja pagar con mis tarjetas de crédito.',
#         'no he podido pagar porque el pase de sura esta fallando.',
#         'por favor revisar por que no me esta llegando las facturas electrónicas a mi correo.',
#         'reclamo devolución de dinero cobrado abusivamente. dos veces cobraron. llevo 20 dias requiriendolos y establecen talanqueras.',
#         'he tenido 3 descuentos de mi cuenta bancaria y todos por concepto del plan plus que tengo como titular. requiero una explicación o una devolución del dinero.',
#         'se presentó un inconveniente con dos pagos seguidos que se debitaron de forma automática correspondientes al pago del mismo mes.',
#         'la factura no está disponible. tengo que llamar para pedir la factura cada mes.',
#         'me hicieron dos cobros del mismo valor.',
#         'doble deducción de mi cuenta de ahorros realizada por ustedes.',
#         'tuvimos problemas para pagar por el código del banco, no teníamos el roaming, y ahora encontramos que nos sacaron del sistema',
#         'se ha debitado cuatro veces en un solo mes el pago de la poliza de salud',
#         'no se evidencia los pagos en plan complementario.',
#         'en el mes de marzo debitaron $840.160 pesos de mi cuenta bancaria por el seguro de medicina prepagada. valor errado, el valor correcto es $596,571.',
#         'aplicar recaudo a la poliza salud.',
#         'me aparece pendiente el recibo de marzo y yo ya lo pagué. por favor corregir esto para estar a paz y salvo.',
#         'me cobraron 4 veces la cuota mensual por débito automático.',
#         'realicé el pago del recibo, dicho pago aparece descontado de la cuenta de ahorros. sin embargo, en el sistema aun aparece esa factura pendiente por pagar.',
#         'se le esta haciendo otro cobro del mismo periodo pero con valor incrementado.',
#         'solicito habiliten las facturas de mi poliza ya que no están cargadas',
#         'los pagos que he realizado no aparecen en el sistema voviendome a cobrar',
#         ],


#     'RECLAMACIONES': [
#         'corregir autorización.',
#         'aún no le han generado la orden para reclamar los medicamentos. por favor validar y generar autorización.',
#         'solicité reembolso por gasto medico en el exterior, a la fecha no he recibido ninguna respuesta.',
#         'solicitando que por favor le ayuden generando la orden de nuevo, ya que cuando la revisaron en el prestador, la orden ya estaba anulada',
#         'activación de la orden ya que la anularon pero no indicaron el motivo, necesita activarla para hacer el cambio de prestador.',
#         'estoy solicitando un reembolso de mi poliza, en dos ocaciones dicen que el adjunto no llega.',
#         'me dicen que la orden está mala.',
#         'requiere renovar la autorización.',
#         'la orden sigue estando a nombre de urogine y de la clínica medellin lo cual no les sirve.',
#         'la orden dice control y debe de decir es consulta.',
#         'solicité reembolso de factura y me la objetaron en 2 ocaciones justificando que no tiene cobertura.',
#         'modificación de la autorización ya que en el prestador le indican que las citas son presenciales y la orden se encuentra generada virtual.',
#         'problemas en la autorización ya que le salio para un prestador donde no le esta haciendo el seguimiento.',
#         'solicita que le ayuden con la autorización ya que se encuentra anulada.',
#         'solicitando la modificación sobre esta orden ya que indica que debe salir bajo el convenio actividad y no por compras por volumen.',
#         'no fue posible que me generaran la autorización.',
#         'me dijeron que la póliza sí cubría pero por reembolso, la asesora lo hizo y lo negaron.',
#         'la orden está anulada.',
#         'le indicaron que no podían realizarlo ya que la autorización se encontraba anulada.',
#         'el reembolso debió de ser mayor.',
#         'necesita que se le autoricen los medicamentos.',
#         'la orden de servicio quedó mala.',
#         'petición para autorizar examenes y procedimientos ordenados.',
#         'autorización de los exámenes',
#         'reenviar las autorizaciones ya que al tratar de descargarlos del sistema no fue posible.',
#         'solicitud de autorización.',
#         'errores, inconsistencias y demoras en las autorizaciones de mi póliza de salud.',
#         'informa que le falta la autorización.',
#         'solicitud de cambio de médico en autorización.',
#         'solicito urgente de autorización.',
#         'se ha solicitado en varias ocasiones autorización de medicamento y no se ha obtenido respuesta.',
#         'solicito a ustedes urgente autorizacion de mis formulas enviadas a ustedes en varias ocasiones.',
#         'usuaria solicita reembolso',
#         'reembolso solicitado sin respuesta afirmativa',
#         'solicito una explicación sobre por que este año las facturas estan siendo reembolsadas por la mitad del valor del reembolso del año pasado',
#         'me rechazaron el reembolso.',
#         'solicité un reembolso a mi cuenta de ahorros y a la fecha no aparece el reembolso',
#         'mi solicitud de reembolso aparece como "pagada" pero no he recibido el dinero..',
#         'hice una solicitud de reembolso pero aparentemente no fue aprobada y no entiendo el motivo.',
#         'solicitud de reembolso anteriormente negada por soportes.',
#         'me fueron autorizadas dos facturas para pago por reembolso, sin embargo, solo recibí un pago.',
#         'reconsideración frente a negación del siniestro.',
#         'solicité reembolso por mi cita por fuera de la red de sura y me reembolsaron un valor inferior al de siempre.',
#         ],


#     'EVALUACION': [
#         'no se ha podido continuar con el proceso para adquirir póliza de salud, argumentando que existe un riesgo estándar financiero.',
#         'expongo los argumentos legales y constitucionales que respaldan mi solicitud para el ingreso al plan preferencial salud para todos. solicito amablemente la reconsideración de la negativa.',
#         'solicito por favor validar en la base de salud sura, mi información consultable o riesgo subnormal que tenga cargada, puesto que he sido rechazado para tomar un crédito por bancolomiba indicándome que en la base de datos de salud sura tengo marcada una preexistencia, y deseo sea desmontada.',
#         'me negaron el ingreso a póliza de salud por tener una preexistencia no asegurable.',
#         'salió declinado ya que no pudo ingresar al plan salud para todos integral y quiere saber el motivo del por qué salió declinado.',
#         'me niegan el ingreso a la póliza por la condición de salud que reporta mi historia clínica.',
#         'por favor solicito de manera formal y por escrito por qué no es viable mi poliza salud.',
#         'motivo por el cual no estoy siendo aceptado en el plan complementario para dos. necesito saber el por qué no soy aceptado.',
#         'solicito por medio de una poliza colectiva estar en la poliza y me dicen que no es posible por una preexistencia.',
#         ],


#     'SERVICIO': [
#         'cliente notifica que no le estan cargando los puntos de ejercicio de plan de recompensas',
#         'se comunico en reiteradas ocasiones con la línea y no recibió una buena atención, la direccionaron al audiorespuesta y colgaron las llamadas e incluso la hicieron esperar 30 minutos en una de ellas, sin respuesta alguna.',
#         'es indignante que se llame a la línea, lo dejen a uno 18 minutos pasando de asesor en asesor para que lo comuniquen a uno a extensiones que no corresponden.',
#         'quejarme de la atención de yaneth luna en la línea de seguros salud. no responde las inquietudes y cierra el chat sin esperar el tiempo prudente para hacerlo por inactividad.',
#         'el robot que contesta para dar las citas en el #888 te dice que no recoce tu voz y que te comunicará con un asesor pero siempre te cuelga.',
#         'me bloquearon el chat de whatsapp, la última comunicación fue que me iban a pasar a un agente y ahí quedó, no se ha comunicado nadie conmigo y cuando escribo no pasa nada.',
#         'mi queja es el por que dan informacion errada.',
#         'problema realizar comunicación con el #888 en el cual le ha tocado llamar hasta 5 o 6 veces.',
#         'inconformidad con las representantes de la línea de atención, la dejan esperando por lo que despues de 10 minutos le toca colgar.',
#         'inconforme con el servicio del voice bot ya que es muy complicado al momento de usarlo.',
#         'no me parece indicado el proceso de la línea de atención para dar información.',
#         'mi queja es con respecto a la línea, es muy difícil comunicar con la inteligencia artificial que manejan. siempre me demora mas de una hora intentando tener comunicacion con ustedes o muchas veces es imposible por el sistema que tiene programado.',
#         'no me gusto la forma de su llamada.',
#         'me quejo en el callcenter.',
#         'le esta llegando información sobre la señora diana olarte, dice que no se conocen de ningun lado, que no sabe por que le llega información sobre ella.',
#         'el bot es muy demorado, lento y confuso; es mejor hablar con un humano porque la atención se hace mucho mas ágil.',
#         'su línea de whatsapp no funciona, no sale ningun menú.',
#         'duré más de una hora hablando con una maquina, lo peor es que ese robot no entendía mi petición.',
#         'cada vez que hay resultados de pruebas para alguna persona llamada sandra patricia me envian los resultados. recibo 4 correos electrónicos casi cada dos semanas para esta persona. me preguntaba si pueden eliminar mi dirección de correo electrónico de la cuenta de esa persona para no recibirla más.',
#         'la companera no fue muy empática, su actitud no fue la adecuada y la senora ana se sintió muy molesta por su actitud por la cual desea colocar la queja.',
#         'he tratado que contactarme por multipes canales y es imposible.',
#         'inconformidad con el ivr, ya que este no logra identificar la tarjeta de identidad.',
#         'al momento que el conmutador le indica que la va a trasferir se cae la llamada',
#         'para el nuevo servicio de conmutador automatico de la linea #888 he llamado 8 veces fallidamente en diferentes dias de la semana, ya que el sistema siempre indica que el documento registrado no registra en el sistema',
#         'el sistema indica que me va a comunicar con un asesor, pero inmediatamente se corta.',
#         'Una llamada con largas pausas, en las que uno debe preguntar si sigue en la llamada.',
#         'en horas de la madrugada le escribieron diciendo que tenian informacion de ella que solo sura sabe.',
#         'recibió una llamada supuestamente de sura, donde preguntaban por el esposo, ella indica que el esposo no se encuentra y que le dejen la razón, le preguntan que a que horas regresa el esposo, ella indica que el esposo esta de viaje y no le podia responder, la persona no deja la razón y cuelga la llamada.',
#         'he llamado al #888 y ha sido imposible, me pasan hasta 6 personas y no dan con mi solicitud, llamar a la línea de servicio es lo mas desgastante.',
#         'al whatsapp le llega una confirmacion de cita, pero que ella no conoce la persona. la llaman toda la semana.',
#         'puntos de plan vive mas',
#         'queja por plan vive mas redencion de puntos',
#         'inconvenientes con programa vive mas.',
#         'inconsistencia con redimir los puntos vive mas',
#         'hice una redención de puntos en el de recompensas y el pdf ya no abre me pueden ayudan por favor',
#         'hice una redención en el plan de recompensas para 2 boletas de cine colombia. no he recibido el correo con los códigos para comprar las boletas.',
#         'solicita envio del cupón por redención de crepes and wafles porque no le llega al correo,',
#         'no le han llegado los puntos que ya redimió',
#         'hace una semana no muestra la acumulación del tiempo de mis caminatas.',
#         'hice redención de puntos a traves de vive mas. pero nunca me llegó el bono.',
#         'cliente inconforme, indica recibir correos de factura que no son suyos.',
#         'me llego un dictamen o sentencia de ustedes de algo ajeno a mí.',
#         'no enviar notificaciones de ningun motivo al senor julian garcia suarez.',
#         'me han estado llegando correos de sura a nombre de luz elena arredondo, no la conozco y no entiendo porque está asociada a mi correo.',
#         'amablemente les solicito que no me envien mas mensajes ofreciendo el servicio de longevo. de verdad que he recibido al menos 10 mensajes y no me interesa el servicio.',
#         'le esta llegando mi informacion personal a la sra. juliana echavarria arboleda cuyo correo es jechava4@eafit.edu.co, agradezco no le siga llegando mis datos a ella que es una informacion confidencial.',
#         'he solicitado que no se me envie correos ni sms con informacion de productos de sura. sin embargo, me siguen llegando. en cumplimiento de la ley de protección de datos solicito que se me excluya definitivamente de cualquier base de datos para envio de informacion promocional de eps sura o de mi poliza de salud.',
#         'ayuda para sincronizar mis actividades de ejercicio en vive mas',
#         'la información que migró a vive mas de la aplicación apple health no está completa.',
#         'quería realizar el registro a smartfit a traves del convenio, pero no me lo permite. me aparece que no es posible completar la solicitud',
#         'realice una redención de puntos en el plan viva mas y no me llego el bono a mi correo. me descontaron los puntos pero me me llego el bono. también revisé en el spam',
#         'redimí unos puntos, pero no me llegó ningun correo y por lo tanto, no he podido hacer efectivo el bono',
#         ],


#     'DIGITAL': [
#         'por la app no le es posible agendar citas.',
#         'solicitando una revision de su app de seguros sura ya que esta intentando registrar a su hijo a una nueva app y le sale que tiene los datos erroneos.',
#         'no he podido acceder a mi cuenta en sura. ni en la pagina web ni en la aplicación. nunca llegan los correos de recuperación ni los mensajes otp.',
#         'lo intento desde 3 computadores distintos, celular y siempre me sale error',
#         'inconvenientes con la app',
#         'problemas para recordar o cambiar clave sura',
#         'fallas app móvil',
#         'tiene incovenientes con la app sura seguros',
#         'el sistema no me permite sacar una cita de forma virtual',
#         'novedad presentada en su plataforma para la selección de citas desde su app de seguros sura.',
#         'usuaria requiere solicitar citas por la app',
#         'inconsistencias para crear la cuenta de sura',
#         'usuaria presenta inconvenientes al asignar citas por la página .',
#         'no han podido crear la cuenta por la app movil',
#         'la pantalla de la app se queda congelada.',
#         'le sale error en la app en el apartado de citas',
#         'solicita restablecimiento de contrasena ya que por ninguno de los medios se lo permite',
#         'inconvenientes con la pagina web',
#         'no le es posible crear la cuenta en la app de sura.',
#         'no permite crear usuario en la sucursal virtual personas',
#         'intenta crear clave y usuario y no la deja sale en blanco y no le permite ingresar al portal web',
#         'error en segurossura.com no deja actualizar en gestion el correo para restablecimiento de la clave',
#         'presenta novedad tecnica no le permite el ingreso a la plataforma',
#         'el correo para recuperar la contraseña no me llega',
#         'información de cómo recuperar su contraseña',
#         'no me deja crear mi usuario porque no me reconoce',
#         'se solicita apoyo no me permite ingresar a crear mi usuario y contrasena del app seguros sura.',
#         'el portal sucursal virtual personas para solicitar reembolso no funciona, me lleva a la pantalla de actualizar datos y el boton de continuar no funciona',
#         'no me permite ingresar a mi plataforma y el correo para recuperar la contraseña está desactualizado',
#         'estoy tratando de retirar un disponible que tengo en bolsillo sura a mi cuenta y no me esta permitiendo,',
#         'no tengo acceso a pedir citas por la web',
#         'inconvenientes para ingreso a plataforma de la página no reconoce documento de identidad',
#         'restablemecimiento de contraseña',
#         'mal funcionamiento del canal de seguros sura sucursal virtual personas.',
#         'necesita una cita virtual se intenta hacer la creación del usuario pero no le hace el envío del mensaje de texto',
#         ]
# }


# CAUSES_EXAMPLES = {

#     'DISPONIBILIDAD_CITA': [
#         'lleva casi mes y medio intentando obtener una cita y le informan repetidamente que no hay agenda disponible.',
#         'solicita ayuda con la programación de la cita, ya que acudió presencialmente y le indicaron que no hay agenda habilitada.',
#         'se comunica solicitando cita, pero le informan que la disponibilidad es a muy largo plazo y no acepta esperar ese tiempo.',
#         'no le asignan ninguna cita porque no hay agenda disponible.',
#         'solicita agilidad en la asignación de la cita para este examen.',
#         'le indican que actualmente no cuentan con agenda para asignar citas.',
#         'las citas disponibles se asignan a casi dos meses; solicitó el 18 de marzo y la única opción fue el 30 de abril de 2025.',
#         'indica que no le asignan cita con oportunidad y que requiere atención prioritaria.'
#     ],


#     'NO_PRESTACION': [
#         'el prestador le informa que no cuenta con convenio vigente para realizar esta atención.',
#         'solicitó la prestación del servicio y le fue negada.',
#         'acudió a clínicas del listado en convenio, pero en ninguna le prestaron la atención a su hijo.',
#         'le indican que el médico no puede atenderla porque la póliza no tiene cobertura para ese servicio.',
#         'la visita domiciliaria nunca se realizó.',
#         'el prestador se negó a realizar el procedimiento.',
#         'finalmente no se realizó la visita ni hubo prestación del servicio.',
#         'la doctora decidió no atender la cita y no se realizó la consulta.'
#     ],

#     'DIAGNOSTICO_TRATAMIENTO_MED': [
#         'la profesional que lo vio no le revisó los oídos, nariz, no lo examinó físicamente, lo único que hizo fue tomar la temperatura y dice que la consulta no duro mas de 5 minutos.',
#         'usuaria confirma que le han hecho un mal procedimiento, que gracias a este procedimiento se encuentra con muy poca movilidad en el brazo.',
#         'usuaria manifiesta inconformidad, ya que desde días pasados su hija ha venido presentando mucho dolor abdominal, la ha llevado más de cuatro veces a urgencias, a médicos generales, pediatras, por urgencias no le hicieron exámenes tipo ecografía abdominal solo de laboratorios, la señora le solicitó a los médicos una ecografía para detectar apendicitis, pero ninguno de ellos se la daba.',
#         'le expliqué al médico que he estado en tratamiento para sobrepeso e higado graso, por lo cual le pedia incluir el examen de tiroides en el listado. el medico negó la solicitud indicando que mi resultado de examen tiroides era bueno y suficiente.',
#         'la doctora no quizo ordenar todos los examenes de sangre que cada año me hacen, solo me ordeno algunos.',
#         'no me pusieron protector gonadal ni de tiroides en un estudio de tc de rodillas. la señora dijo que no era necesario por mi edad.',
#         'después de dar los signos y de referir que viene con fuerte dolor abdominal y que ha presentado desmayo y vómito, me dicen que los signos están bien que debe esperar. necesito que revisen si los servicios de triaje se hacen a conciencia y con los profesionales idóneos para la actividad',
#         'me gustaría pedir una segunda lectura de estos exámenes ya que en los resultados dice que tengo "vesícula distendida", y a mi me sacaron la vesícula hace como 3 años... entonces la verdad no confío y me gustaría una segunda lectura.',
#     ],

#     'ATENCION_PRESTADOR': [
#         'el auxiliar alejandro diaz fue muy irrespetuoso y su actitud no es de servicio ni orientación. su lenguaje gestual y verbal desorienta y agrede. parece que tuviera dolor profundo, pues su cara es despedidora, agresiva y poco empatica. me malorientó y me hizo perder mi turno cuando lo estaba solicitando.',
#         'me encuentro muy insatisfecho con la atención recibida por parte de katherine andrea molina gallo, fue pésimo no me miro a los ojos y me atendió de manera grosera y displicente.',
#         'la persona de mikaela que da el refrigerio, lo entrega de mala aptitud como si el refrigerio ellas lo regalaran, no es un buen servicio, se siente uno pidiendo limosna.',
#         'recibí la atención de la doctora y su orientación fue muy despectiva. demasiado indiferente y grosera al comunicarse con los pacientes, deberían reevaluar como están prestando el servicio y que tan humano es.',
#         'el profesional estaba viendo porno el trato regular e impersonal',
#         'presento queja sobre la mala atención del personal de caja, son groseras al atender el público, irrespetuosas',
#         'con sebastian restrepo he tenido inconvenientes porque asume que por yo llevar tiempo debo saber todo y pienso que cada vez que vengo necesito asesoría.',
#     ],

#     'DEMORA_PRESTACION': [
#         'le indicaron que el médico llegaría en máximo 4 horas, pero el tiempo se extendió sin cumplir lo informado.',
#         'en dos citas consecutivas tuvo retrasos de más de una hora para ser atendido.',
#         'atienden primero a personas que llegaron después, a pesar de tener cita asignada.',
#         'el médico domiciliario tardó más de 12 horas en llegar.',
#         'tenía cita a la 1:40 pm y más de una hora después aún no había sido atendido.',
#         'desde el día anterior está esperando la aprobación para asignación de cuarto sin respuesta.'
#     ],

#     'COMUNICACION_PRESTADOR': [
#         'intenta comunicarse por teléfono y no obtiene respuesta.',
#         'trata de contactarse con la doctora por el número de whatsapp registrado y no recibe respuesta.',
#         'al llamar, el sistema solicita datos y luego dejan la llamada en espera sin responder.',
#         'se comunica en repetidas ocasiones y no le contestan.',
#         'al llamar al número del directorio médico, cuelgan la llamada al seleccionar la opción de citas.',
#         'ha realizado más de 100 llamadas sin lograr comunicación ni por teléfono ni por la página web.',
#         'indica que el prestador nunca responde los intentos de contacto.'
#     ],

#     'CANCELACION_CITA': [
#         'le cancelaron dos citas ya programadas sin haberlo solicitado ni notificado.',
#         'recibió una cancelación de la cita de su hijo por error.',
#         'tenía una cita programada en una sede específica y posteriormente fue reprogramada a otra ciudad.',
#         'inconforme porque una cita previamente asignada fue reprogramada para otra fecha.',
#         'acudió a la cita programada y le informaron que había sido reprogramada sin confirmación previa.'
#     ],

#     'CUOTA_MODERADORA': [
#         'usuaria solicita queja, ya que le estan generando cobro de cuota moderadora de atención.',
#         'usuaria solicita la devolución de un copago, pagado el día de hoy 05 de junio de 2024, concepto cita de telemedicina interna.',
#         'la persona que atendía le cobró a mi compañera casi $100.000. no se supone que tenemos una bolsa a nuestro favor para esos exámenes? entonces, porqué hoy cobraron caso $ 100.000. solicito una explicación y la devolución de ese dinero.',
#         'mi queja es porque me están cobrando copago en la atención de mi poliza salud para todos, cuando me dicen que estamos exentos de copagos.',
#     ],

#     'DEMORA_RESULTADOS': [
#         'el sábado me realice una prueba de covid y aun no tengo los resultados.',
#         'el 5 de agosto me realizaron un score de calcio, el examen no aparece en la aplicación, en la sede industriales me aseguraron que el resultado llegaba el 12 y hasta ahora, nada.',
#         'son las 8:30 pm y aun no tenemos resultados mi prescripcion',
#         'unos exámenes que normalmente estaban el mismo día, aquí se demora en 5 días',
#         'me dijeron que en 10 días hábiles máximo tendría el resultado. este tiempo ya se cumplió y no tengo respuesta. tampoco aparece como un examen pendiente en la página. necesito saber qué pasó con este resultado y cuándo me lo entregan.',
#     ],

#     'ENTREGA_MEDICAMENTOS': [
#         'no ha sido posible la entrega de su medicamento, se valida y el medicamento se encuentra agotado.',
#         'solicito por favor me entreguen a domilicio el medicamento que estaba para el 1 de mayo de este 2024 y a la fecha hoy 5 mayo del 2024 nada que esta habilitada la opcion de domicilio.',
#         'el profesional le envía el medicamento, el personal de la farmacia en colsubsido le indica que se comunique a radicar la queja porque no saben cuando llegará el medicamento.',
#         'envié foream a farmacovigilancia para entrega de keppra y lamictal. me dicen de neuromédica que el foream lo cancelaron del sistema y que solo me entregan los genéricos. en repetidas ocasiones he tenido que comprarlos particularmente.',
#         'no me han entregado mas medicamentos y me estoy viendo afectado.',
#     ],

#     'AUTORIZACIONES': [
#         'tiene una orden para terapias físicas, pero el día de hoy le indicaron que solo le habían generado 1 porque ya había cumplido el tope que tiene dentro de su póliza.',
#         'no estoy de acuerdo con la negación de la solicitud donde la causa es por patologías del feto y aborto provocado y yo no tengo nada que ver con eso, las políticas dicen que si se inicia el parto estando dentro de la póliza todo el embarazo tiene cobertura.',
#         'solicité autorización para un examen genético a mi hija y fue rechazado.',
#         'prestador le informa al paciente que la autorización tiene que ser por actividad cambiarlo por favor',
#         'se comunica paciente solicitando nuevamente el cambio de prestador.',
#         'se comunica usuaria solicitando que por favor le corrijan la autorización ya que la autorizaron por 1 frasco y son por 5.',
#     ],

#     'REEMBOLSOS': [
#         'he pedido reembolso varias veces de mis citas con el psiquiatra y nunca recibo una respuesta.'
#         'el último reembolso de mi póliza de salud autorizado, fue consignado a la cuenta bancaria del tomador de la póliza sin justificación alguna; más aún cuando en la aplicación seleccioné específicamente que se consignara en mi cuenta bancaria.',
#         'solicito a sura que realice el pago en su totalidad los gastos médicos por concepto de la atención médica y procedimientos realizados a mi hija en la clínica.',
#         'se comunica usuario a validar varias solicitudes de reembolso el cual no se le aprobó ya que las consulta por neuropsicología carecen de cobertura del plan de salud.',
#     ],

#     'DESCONTENTO_PRODUCTO': [
#         'manifiesta inconformidad porque la póliza de salud no cumple con las coberturas y beneficios ofrecidos al momento de la contratación.',
#         'indica que la póliza adquirida no presenta diferencias reales frente a los servicios de la eps, a pesar de haber contratado un plan adicional.',
#         'queja por incumplimiento de las condiciones contractuales de la póliza de salud.',
#         'señala que los beneficios del producto contratado no corresponden a lo estipulado en el contrato.',
#         'expresa descontento porque la póliza no satisface las expectativas ni las necesidades para las que fue adquirida.',
#         'manifiesta inconformidad con el producto, ya que las coberturas ofrecidas no se reflejan en la atención recibida.'
#         'se adjunta queja y soporte en archivos adjuntos',
#         'por medio del presente adjunto derecho de petición',
#         'anexo carta queja'
#     ],

#     'ATENCION_ASESOR': [
#         'inconforme con la asesora ya que dice que siempre que la llama lo que le responde es que en el momento no la puede atender.',
#         'usuaria solicita por favor se le realice el cambio de asesor por motivo de que le escriben por whatsapp le envian correo y no le contesta.',
#         'en el momento de la comunicación con el asesor de televentas la información sobre las coberturas del seguro eran completamente diferentes a lo acordado, se siente estafado.',
#         'compré una póliza de salud para todos que me vendió una asesora dónde me aseguro que tenía cobertura en mi lugar de residencia, el día de hoy solicité un servicio de atención donde me dicen que no tiene cobertura en jamundí ni ningún otro operador por lo cual me siento engañado con la venta.',
#         'cliente se comunica a la línea solicitando una queja por informacion errada en venta de poliza',
#         'solicite la terminación de mi póliza el día de la fecha de corte, pero la asesora ha tenido una actitud negligente y de desatención completa.',
#         'cliente radica queja, se percata que la información que le brindaron del producto es totalmente falsa, dado que las coberturas no son lo que le informaron.',
#     ],

#     'EXPEDICION_SIN_AUTORIZACION': [
#         'he sido suscrito a una póliza de salud sin atender los protocolos previstos y sin mi consentimiento ni firma. requiero la cancelación inmediata de la misma',
#         'no tengo ninguna poliza con ustedes, no tengo ningun contrato con ustedes. necesito que me cancelen cualquier vinculo comercial que tenga con ustedes',
#         'sura me esta haciendo un descuento a mi cuenta de ahorros de bancolombia de un supuesto plan odontologico, el cual no he suscrito y ni siquiera pertenezco a esa eps por lo anterior solicito la supension de dicho cobro automatico por un plan que no disfruto, ni conozco, ni he solicitado.',
#     ],

#     'ERROR_FACTURACION': [
#         'no me está llegando la factura electrónica del seguro.',
#         'usuario se comunica ya que no le permite pagar la factura, se valida y registra pagada, con lo cual no conrresponde porque él indica que no la ha pagado.',
#         'no volver a debitar de ninguna de mis cuentas el valor de la póliza de salud y aun así, lo siguen haciendo, estoy al día, ni siquiera estoy debiendo y me debitan sabiendo que no tienen autorizado.',
#         'les solicito por favor corregir los recibos de pago. al consultar los recibos para realizar el pago de junio me encontré con inconsistencias.',
#     ],

#     'DEMORA_CANCELACION': [
#         'estoy soliciando la cancelacion de la poliza de salud colectiva, agradezco me ayuden con esta cancelación.',
#         'solicito el retiro del servicio del plan complementario ya que no lo uso ni llena mis espectativas.',
#         'yo hice una solictud de retiro de una poliza y veo que continúa vinculado a la póliza solicité el retiro de uno de mis asegurados en la poliza y aún no lo retiran',
#         'deseo retirarme.',
#         'realizó la solicitud de cancelación de la póliza de salud colectiva, pero a la fecha no ha sido procesada.',
#         'solicitó el retiro del plan complementario y continúa activo a pesar de haber realizado el trámite.',
#         'radicó la solicitud de retiro de la póliza y verifica que aún sigue vinculada sin que se haya efectuado la cancelación.',
#         'solicitó el retiro de uno de los asegurados y después de varios días aún no se ha realizado.',
#         'hizo la solicitud de cancelación de la póliza y no ha recibido confirmación ni ejecución del retiro.'
#     ],

#     'CANCELACION_SIN_AUTORIZACION': [
#         'recibí un correo donde me decían que mi póliza de salud había sido cancelada, quiero conocer el motivo por el cual me lo están cancelando.',
#         'adjunto derecho de petición y soportes de pago ya que mi poliza de salud fue cancelada sin motivo por error de sura.',
#         'solicito una aclaración respecto a la cancelación de la póliza. quisiera dejar claro que en ningún momento he solicitado la cancelación de dicha póliza. por lo tanto, desconozco las razones por las cuales se llevó a cabo dicha cancelación.',
#         'llegó una carta firmada por mi en donde decia que retirar a mi hijo de mi poliza de salud. gracias a mi asesor pudimos detener ese retiro por que yo nunca envié dicha carta',
#         'me notifican que yo realice la solicitud de la cancelación. en ningún momento me he comunicado solicitando esto.',
#     ],

#     'INCREMENTO_PRIMA': [
#         'agradezco su apoyo indicandome el motivo de aumento de mis dos polizas que tengo contratadas ya que el mes pasado de septiembre pague 310.000 y ahora me estan cobrando 365.000 es un aumento del 18% el cual en el contrato no se indicaba. solicito evaluar el precio para que se no se haga un aumento mayor a la inflación',
#         'aclaración de aumento de valores en póliza',
#         'para el año 2025 el precio se ha incrementado un 100%. este nuevo valor no puedo pagarlo.',
#         'no esta de acuerdo con el aumento del plan.',
#         'la prima de está renovación me llego mas elevada que lo usual.',
#     ],

#     'DOCUMENTOS_ASOCIADOS': [
#         'he pedido muchas veces por medio de su plataforma el certificado de antiguedad y preexistencias pero solo me envian el de antiguedad.',
#         'lo que requiero es el certificado con el valor total de lo pago en el 2023 de mi poliza de salud, considero que hay un error en el certificado.',
#         'trato de generar un certificado de poliza de salud, me sale un un error que dice: error al descargar certificado.',
#         'solicité el certificado de antigüedad y preexistencias, he radicado dos veces el proceso sin obtener respuesta.',
#         'solicité mi historia clínica desde el momento de afiliación a eps sura y pac preferencial y no ha sido posible que ustedes la envíen.',
#     ],

#     'DEVOLUCION_DINERO': [
#         'se comunico la asegurada solicitando devolución del dinero que esta pendiente por cancelación de la póliza.',
#         'a dia de hoy 4 de mayo no me han hecho la devolución de mi dinero.',
#         'tengo un pago a mi favor de 7 meses, el cual nunca hicieron y no me dan ninguna respuesta.',
#     ],

#     'ERROR_EXPEDICION': [
#         'usuaria se comunica ya que hace dos meses solicito el cambio de plan de preferencial a clasico, el asesor le indico que habia realizo el cambio pero no se ha realizado.',
#         'mi hijo recientemente cumplió 18 años, ya tiene la contraseña de la cédula de ciudadanía, he intentado por diferentes medios de cambiar el tipo de documento.',
#         'solicito la actualización de los datos de mi hija luciana rendon.',
#         'inicio sesión con mi cédula de ciudadanía, sale el nombre de mi mamá.',
#         'he solicitado en varias ocasiones la corrección de mi nombre en el sistema. he tenido inconvenientes por esta incongruencia y les solicito que por favor hagan el cambio.',
#     ],

#     'INCONFORMIDAD_RENOVACION': [
#         'no solicité renovación de la póliza de salud, nadie me llamó y por ningún medio autoricé la renovación de la misma, espero se me pueda cancelar esa póliza que se renovó de manera automática.',
#         'me llegó un correo con actualización de renovación de póliza la cual no solicité ni necesito.',
#     ],

#     'APP': [
#         'inconvenientes en la aplicación móvil para solicitar cita únicamente para el niño Isaac Betancourt; para otros usuarios la app funciona correctamente, ya fue desinstalada y reinstalada sin solución.',
#         'no puede restablecer la contraseña desde la aplicación móvil.',
#         'presenta inconvenientes en la app, no le permite crear el usuario desde el celular.',
#         'la aplicación móvil no permite crear el usuario, no llega el código de verificación ni por llamada ni por mensaje de texto.'
#     ],

#     'SUCURSAL_VIRTUAL': [
#         'no ha podido ingresar a la sucursal virtual desde la página web; el sistema solicita cambio de clave pero no permite continuar.',
#         'presenta dificultad para ingresar al portal web de la sucursal virtual para solicitar cita, el sistema indica usuario o clave inválidos.',
#         'la página web de consulta de resultados de laboratorio presenta fallas, ya que descarga resultados incorrectos o incompletos.'
#     ],

#     'LONGEVO': [
#         'la aplicación del programa Longevo no está contabilizando el tiempo de actividad física configurado, por lo que no se están cargando los puntos correspondientes.',
#         'completó las guías del programa Vive Más en la sección de finanzas, pero el sistema no sumó los minutos ni los puntos del programa.',
#         'no puede acceder a la sección de Longevo dentro de la aplicación, ya que su número de celular aparece asociado a otra cuenta.',
#         'el plan Vive Más no permite asociar la aplicación Google Fit para el registro de actividad física.'
#     ],

#     'LINEA_ATENCION': [
#         'inconforme con el servicio del voice bot citas, ya que siempre que trata de comunicarse a la línea para solicitar citas, este le impide porque se demora mucho tiempo para comunicarla con un asesor y es muy engorroso estar repitiendo toda la información.',
#         'inconformidad por las opciones del menú voicebot, ya que lleva mas de media hora tratando de comunicarse con un asesor pero le ha sido imposible navegar por el menú y el robot no entiende.',
#         'llevo varios días intentando comunicarme por chat de whastapp y es imposible llegar a comunicarme.',
#         'hice una llamada al #888 inicialmente me atendió un robot y luego dijo que me iba a transferir con un asesor, llevo una hora dieciocho minutos y nadie contesta.',
#         'servicio de atención telefónica muy demorado, se demoran demasiado en responder las llamadas.',
#     ],

#     'TRATAMIENTO_DATOS': [
#         'está recibiendo correos electrónicos dirigidos a otra persona y solicita la corrección por uso indebido de sus datos de contacto.',
#         'manifiesta inconformidad porque una ips lo está contactando para un programa sin su autorización, cuestionando el uso de sus datos personales.',
#         'reporta vulneración de la protección de datos, ya que información de su historia clínica fue compartida sin consentimiento, afectando su derecho a la privacidad.'
#     ],

#     'PAGO_NO_LEGALIZADO': [
#         'el recibo correspondiente al mes de agosto ya fue cancelado oportunamente; sin embargo, en la plataforma aún aparece como pendiente de pago.',
#         'al intentar pagar las pólizas, el sistema muestra deuda del mes anterior aunque los pagos fueron realizados a tiempo y aparecen en el historial.',
#         'tras realizar los pagos correspondientes, estos no se reflejan en el sistema y le indican que presenta mora de dos meses.',
#         'realizó un pago con tarjeta de crédito que fue debitado, pero el sistema lo registró como rechazado.'
#     ],


#     'DOBLE_COBRO': [
#         'inconformidad por un doble débito automático en el mes de diciembre, porque el cobro que se le ha hecho siempre es mensual.',
#         'indica que el dia 18 de noviembre del 2024 le debitaron dos veces el pago de la poliza de salud por valor $402.632.',
#         'en el mes de octubre me realizaron doble cobro de la poliza de salud clasica. uno el 16 de octubre (es el que me realizan mensual) y otro el 31 de octubre... cada uno de 960 mil pesos.',
#         'se comunica asegurado quien informa que le cobraron 2 veces su póliza de salud el 20 de julio.',
#         'hoy entré a realizar el pago del plan y me salía que debía abril, me pareció extraño, pero hice el pago. ahora revisando los pagos que hice en mayo, veo que realicé el pago de abril el 2 de mayo, es decir, pagué la factura de abril dos veces.',
#     ],

#     'PAGO_EXPRESS': [
#         'al ingresar a la plataforma Pago Express no se visualiza la factura para pagar con el número de recibo 72539119.',
#         'desde la actualización de la plataforma Pago Express se dificulta descargar el recibo de pago como soporte.',
#         'no ha sido posible realizar el pago virtual a través del enlace de Pago Express, por lo que debe desplazarse a bancos.',
#         'el sistema de Pago Express no permite realizar el pago y muestra error del emisor desde hace más de un mes.'
#     ],


#     'NO_COBRO': [
#         'el débito automático se realiza los días 10 de cada mes y a la fecha no se ha efectuado, teme afectación del servicio por mora.',
#         'no ha sido posible realizar los pagos de los meses correspondientes debido a que no se han generado los recibos.',
#         'el cobro del mes de junio aún no se encuentra cargado en el sistema para realizar el pago.',
#         'no se está generando el recibo necesario para pagar el plan complementario.'
#     ],


#     'NO_ACEPTACION': [
#         'solicita información sobre el motivo por el cual no le permiten ingresar o afiliarse a la póliza de salud, indica que se encuentra bloqueada sin una explicación clara.',
#         'la persistencia de un diagnóstico clínico erróneo en su historia médica ha generado la negación injustificada de su afiliación al plan de salud y la imposibilidad de acceder a los servicios.',
#         'fue rechazada para la afiliación a la póliza de salud por presentar sobrepeso y problemas metabólicos, considera que esta no es una razón válida y manifiesta inconformidad con la decisión.'
#     ],
# }


PROCESS_DICT = {
    'FINANCIACION DE POLIZA': 'EXPEDICION',
    'GESTION DE CARTERA': 'RECAUDOS',
    'GESTION DE PAGOS': 'RECAUDOS',
    'ASISTENCIA MEDICA': 'ASISTENCIA SALUD',
    'ASISTENCIA ODONTOLOGICA': 'ASISTENCIA SALUD',
}


CAUSES_DICT = {
    'INADECUADA ATENCION DEL EMPLEADO SURA': 'INADECUADA ATENCION DEL PROVEEDOR/PRESTADOR',
    'INCONVENIENTES CON PROGRAMA VIVE MAS': 'INCONVENIENTES CON PROGRAMA VIVE MAS - LONGEVO',
    'INCONFORMIDAD CON INSTALACIONES LOCATIVAS': 'INADECUADA ATENCION DEL PROVEEDOR/PRESTADOR',
    'DEMORA O NO REALIZACION DE MODIFICACION DE FINANCIACION DE POLIZA': 'DEMORA O NO ENTREGA DE LA POLIZA Y DOCUMENTOS ASOCIADOS',
    'INCONFORMIDAD POR LA DISPONIBILIDAD DE LA RED MEDICA': 'FALTA DE OPORTUNIDAD Y DISPONIBILIDAD PARA CONSEGUIR LA CITA',
    'COBRO A CLIENTE QUE CANCELO EL PRODUCTO': 'ERROR EN FACTURACION O COBRO NO PACTADO',
    'INCONFORMIDAD CON LA FACTURA ELECTRONICA': 'ERROR EN FACTURACION O COBRO NO PACTADO',
    'ERROR EN DATOS PERSONALES DEL CLIENTE': 'ERROR EN LA EXPEDICION',
    'INADECUADO MANEJO DATOS PERSONALES': 'INCONFORMIDAD CON TRATAMIENTO DE DATOS',
    'COBRO A CLIENTE QUE NO TIENE SEGURO': 'ERROR EN FACTURACION O COBRO NO PACTADO',
    'DIFICULTAD TRANSCRIPCION DE INCAPACIDADES - MEDICAMENTOS Y LICENCIAS DE MATERNIDAD': 'INCONFORMIDAD CON EL DIAGNOSTICO/TRATAMIENTO O MANEJO MEDICO',
    'COBRO ANTICIPADO': 'DOBLE COBRO',
    'DEMORA EN LA ATENCION Y/O PAGO EN LA RECLAMACION': 'PROBLEMAS CON REEMBOLSOS DE SALUD',
    'INCONVENIENTES TECNICOS SITIOS WEB': 'INCONVENIENTES GENERALES - SUCURSAL VIRTUAL',
    'INCONFORMIDAD CON EL AUDIO O MARCACION LINEA DE ATENCION-SEDES': 'INCONFORMIDAD EN LA COMUNICACION CON LA LINEA DE ATENCION',
    'INCONFORMIDAD CON ASISTENTE CONVERSACIONAL TIBOT': 'INCONFORMIDAD EN LA COMUNICACION CON LA LINEA DE ATENCION',
    'FALTA DE DISPONIBILIDAD DE VACUNAS': 'NO PRESTACION DEL SERVICIO',
    'INCONFORMIDAD CON EL VALOR COBRADO EN SERVICIOS PARTICULARES': 'INCONFORMIDAD CON CUOTA MODERADORA O COPAGO',
    'ERROR EN INSCRIPCION CUENTAS BANCARIAS': 'INCONVENIENTES GENERALES - SUCURSAL VIRTUAL',
    'PROBLEMAS AL RECLAMAR EL DINERO EN CORRESPONSALES BANCARIOS/OFICINAS': 'PAGO NO LEGALIZADO',
    'DEMORA EN INSCRIPCION DE CUENTA': 'PROBLEMAS AL PAGAR A TRAVES DE PAGO EXPRESS',
    'INCONFORMIDAD CON LA CANCELACION DE LA POLIZA FINANCIADA': 'CANCELACION SIN AUTORIZACION DEL CLIENTE',
    'INCONFORMIDAD CON CONCILIACION O ACLARACION DE MORA': 'PAGO NO LEGALIZADO',
    'INCONFORMIDAD CON EL SERVICIO PRESTADO POR EL PROVEEDOR': 'INADECUADA ATENCION DEL PROVEEDOR/PRESTADOR',
    'INCONVENIENTES TECNICOS ASISTENTE VIRTUAL /CHAT': 'INCONFORMIDAD EN LA COMUNICACION CON LA LINEA DE ATENCION',
    'INCONFORMIDAD CON EL DIRECTORIO MEDICO': 'INCONFORMIDAD EN LA COMUNICACION CON EL PRESTADOR',
}


DESCONTENTO_PRODUCTO = {
    '.',
    'PQR',
    'QUEJA',
    'ERROR',
    'QUEJA.',
    'NINGUNO',
    'LEER CARTA',
    'AFILIACIÓN',
    'ANEO CARTA',
    'LEER ANEXO.',
    'DOC. ADJUNTO',
    'ADJUNTO QUEJA',
    'ADJUNTO CARTA',
    'ADJUNTO PQRS.',
    'FAVOR VALIDAR',
    'ADJUNTO CARTA.',
    'INCONFORMIDAD.',
    'ANEXO PETICION',
    'ANEXO DOCUMENTO',
    'SE ADJUNTA PQR.',
    'SE ADJUNTA CARTA',
    'ADJUNTO SOLICITUD',
    'VER CARTA ADJUNTA',
    'ANEXO CARTA QUEJA.',
    'ADJUNTO SOLICITUD.',
    'REGISTRO DE QUEJAS',
    'VER ARCHIVO ADJUNTO',
    'DERECHO DE PETICION',
    'VER CARTAS ADJUNTAS',
    'ADJUNTO QUEJA A PDF',
    'RESPUESTA A RADICADO',
    'DERECHO DE PETICIÓN.',
    'ADJUNTO QUEJA ESCRITA',
    'ADJUNTO QUEJA EN PDF.',
    'VER DOCUMENTO ADJUNTO.',
    'ADJUNTO CARTA DE QUEJA',
    'ADJUNTO DP DE SERVICIOS',
    'CARTA DE RECLAMO A SURA',
    'REVISAR LA CARTA ADJUNTA',
    'ANEXO DOCUMENTO SOPORTE.',
    'ANEXO CARTA SON PETICION',
    'ESTE SISTEMA NO FUNCIONA.',
    'EN LA CARTA ESTA LA QUEJA',
    'ENVIO DERECHO DE PETICION',
    'BUENOS DÍAS, ADJUNTO CARTA',
    'SE COMUNICA EL SEÑOR KEVIN',
    'SE DA INFO DEL TP 36306149',
    'ADJUNTO CARTA CON MI QUEJA',
    'SE COMUNICA LA SEÑORA PAULA',
    'ADJUNTO DERECHO DE PETICIÓN',
    'ADJUNTO CARTA CON SOLICITUD',
    'ANEXO EN DOCUMENTO MI QUEJA',
    'ADJUNTO QUEJA EN LOS ANEXOS',
    'ADJUNTO DERECHO DE PETICION',
    'SE COMUNICA EL SEÑOR CAMILO.',
    'CARTA CANCELACIÓN DE PÓLIZA.',
    'ADJUNTO, DERECHO DE PETICIÓN',
    'ANEXO ARCHIVO CON DESCRIPCIÓN',
    'ENVIO SOLCIITUD DE ACLARACION',
    'FALLAS EN EL PLAN RECOMPENSAS',
    'ADICIÓN A PQRS 24112433882302',
    'QUEJA SOBRE LA IPS INTEGRARTE',
    'SE COMUNICA ASEGURADO MOLESTO',
    'SE REALIZA CASO EN SALESFORCE',
    'SE COMUNICA LA SEÑORA ISABELLA',
    'SE ADJUNTA DERECHO DE PETICIÓN',
    'RADICACION DERECHO DE PETICION',
    'SE ADJUNTA DERECHO DE PETICION',
    'RADICACIÓN DERECHO DE PETICIÓN',
    'ASEGURADA ENVIA QUEJA VIA EMAIL',
    'SE COMUNICA USUARIA, INDICA QUE',
    'SE ADJUNTA DERECHO DE PETICIÓN.',
    'ADJUNTO COPIA CARTA DE PETICIÓN',
    'ADJUNTO ENVÍO ANEXO LA PETICIÓN',
    'POR FAVOR REVISAR CARTA ADJUNTA.',
    'SU AYUDA CON ESTE TEMA POR FAVOR',
    'BUEN DIA, \n\nREVISAR CARTA ADJUNTA',
    'INCONFORMIDAD SEGUN CARTA ADJUNTA',
    'SE ADJUNTA VIDEO Y AUDIO DE QUEJA',
    'SE COMUNICA LA SEÑORA MARTA VELEZ',
    'ADJUNTO COMUNICACIÓN CON LA QUEJA',
    'POR FAVOR VER COMUNICACIÓN ADJUNTA',
    'SE COMUNICA LA SEÑORA  MARTA VELEZ',
    'SE COMUNICA EL SEÑOR  WILFER SERNA',
    'DERECHO DE PETICION PATRICIA SAIEH',
    'RECLAMACIÓN ? CANCELACIÓN DE POLIZA',
    'LOS COMENTARIOS ESTAN EL EL ADJUNTO',
    'ASEGURADO NO REMITE QUEJA POR EMAIL',
    'SE ENVIA CARTA CON EL RECLAMO/QUEJA',
    'ADJUNTO DOCUMENTO QUE CONTIENE QUEJA',
    'NO ENCUENTRO RESPUESTA A MI SOLICITUD',
    'EN OFICIO ADJUNTO SE DETALLA LA QUEJA',
    'SOLICITUD  PÓLIZA NÚMERO: 090001555593',
    'SE COMUNICA AL SEÑORA  GLORIA SEPULVEDA',
    'LA QUEJA SE ENCUENTRA EN EL ARCHIVO PDF',
    'VER ARCHIVO .PDF  ANEXO CON LOS HECHOS.',
    'BUENOS DÍAS, ENVÍO ADJUNTO RECLAMACIÓN.',
    'ANEXO CARTA CON EL DETALLE DE LA QUEJA.',
    'DERECHO DE PETICIÓN  VERIFICAR ADJUNTO.',
    'ADJUTO SE ENVÍA PETICIÓN EN ARCHIVO PDF.',
    'SE ANEXA ARCHIVO EXPLICANDO LA SITUACIÓN',
    'SOLICITA QUEJA DE LA PÓLIZA BAN109568049',
    'SE ADJUNTA CARTA CON DERECHO DE PETICIÓN.',
    'GRACIAS POR SU RAPIDA GESTION Y RESPUESTA',
    'LOS DETALLES ESTÁN EN EL DOCUMENTO ADJUNTO',
    'ADJUNTO REMITO UNA PETICIÓN CON DOS ANEXOS.',
    'POR FAVOR REVISAR CARTA ADJUNTA A ESTA QUEJA',
    'BUEN DÍA, FAVOR LEER CARTA ADJUNTA. GRACIAS.',
    'POR FAVOR DAR SOLUCION A LA PETICION ADJUNTA',
    'DI050052805 LILIAM CARDEÑO ACERO CC 42776043',
    'ADJUNTO CORREO ELECTRÓNICO QUEJA DEL CLIENTE',
    'ENVÍO ARCHIVO ANEXO CON DERECHO DE PETICIÓN.',
    'CORDIAL SALUDO, ADJUNTO DERECHO DE PETICION.',
    'DI050412357 JENNY SERNA DE DUSSAN CC 20339441',
    'PETICION SOBRE MI POLIZA DE SALUD. ANEXO CARTA',
    'SOLICITUD DE INFORMACION SOBRE POLIZA DE SALUD',
    'BUENOS DÍAS DESEO CANCELAR MI PLAN PREFERENCIAL',
    'BUENAS TARDES, \n\nVALIDAR INFORMACIÓN SOLICITADA',
    'ADJUNTO DOCUMENTO CON DESCRIPCIÓN DE LOS HECHOS',
    'PÓLIZA N°: 090001540797 SALUD PARA DOS FAMILIAR',
    'SE REALIZA QUEJA POR INCONFORMIDAD EN LA POLIZA',
    'SE ADJUNTA QUEJA Y SOPORTE EN ARCHIVOS ADJUNTOS.',
    'ASEGURADA SE COMUNICA MANIFESTANDO INCONFORMIDAD.',
    'INCONFORMIDAD RESPUESTA A UN DERECHO DE PETICIION',
    'DI050054293 MARÍA EMMA CARDONA OSPINA CC 32417080',
    'SE COMPARTE DERECHO DE PETICIÓN LEY 1755 DE 2015.',
    'SE ADJUNTA DERECHO DE PETICIÓN PARA DAR RESPUESTA',
    'SE RADICA QUEJA ASEGURADO PÓLIZA 800268 CC.5918275',
    'POR MEDIO DEL PRESENTE ADJUNTO DERECHO DE PETICIÓN',
    'ADJUNTO EL ARCHIVO DE MI PETICIÓN A ESTA SOLICITUD.',
    'ADJUNTO CARTA DE RETIRO SOLICITADO DESDE JULIO 2025',
    'ADJUNTO DERECHO DE PETICIÓN PARA SU PRONTA GESTIÓN.',
    'ME CIÑO A LOS ARGUMENTOS EXPUESTOS EN EL PDF ADJUNTO',
    'ASESORA COMERCIAL CON CODIGO 10269 DESEA PONER QUEJA',
    'INCONFORMIDAD EN LA ATENCION DE LA POLIZA ENTRE OTROS',
    'DI047193380- MARIA EUGENIA ZAPATA USUGA CC 1020440414',
    'MEJOR SISTEMA ANTERIOR, ESTE MUY COMPLICADO E INCOMODO',
    'ADJUNTO UNA CARTA EN FORMATO PDF DONDE RADICO MI QUEJA,',
    'DI050051333 ÁNGELA MARIA CASTRILLON CADAVID CC 42757559',
    'ADJUNTO SOLICITUD. \n\nQUEDANDO ATENTA A SUS COMENTARIOS.',
    'ENVÍO ARCHIVO DE HISTORIA CLÍNICA SOLICITADA POR USTEDES',
    'ADJUNTO DOCUMENTACIÓN REFERENTE AL CASO. \n24121634030092',
    'INSATISFACCIÓN DEL SERVICIO PARA EL POLIZA PLAN SURA PAC',
    'DI048469062 ROSANA PALOMA PIEDRAHÍTA GARCÉS CC 66959532.',
    'ADJUNTO QUEJA FORMAL DE LA POLIZA DE SALUD NO 09000107454',
    'AGRADEZCO RESPUESTA A LA SOLICITUD SEGUN ADJUNTO. GRACIAS',
    'BUENOS DIAS \n \nQUEDO A LA ESPERA DE UNA PRONTA RESPUESTA.',
    'RESPUESTA URGENTE A MI QUEJA Y/O SOLICITUD 25080835745306',
    'AMABLEMENTE ME PERMITO REMITIR ADJUNTO DERECHO DE PETICIÓN.',
    'ADJUNTO DERECHO DE PETICION DIRIGIDO A SEGUROS SURAMERICANA.',
    'ADJUNTO IMAGEN DE DOCUMENTO, PARA SU CONOCIMIENTO Y GESTIÓN.',
}


CAUSAS_ELIMINAR = {
    'PERDIDA ECONOMICA POR PRESUNTO FRAUDE EXTERNO',
    'PUBLICIDAD ENGAÑOSA',
    'PERDIDA DE DOCUMENTOS ENVIADOS POR EL CLIENTE',
    'DEMORA EN SERVICIO REQUERIDO PARA EMISION DE POLIZA',
    'INADECUADA ATENCION POR PRESUNTO ACOSO SEXUAL',
    'INADECUADA ATENCION DEL MEDICO EN LINEA',
    'INCONVENIENTES CON LA INFORMACION DE TU BIENESTAR AL DIA',
    'PAGO NO ABONADO POR ASESOR',
}

PROCESOS_ELIMINAR = {
    'RECLAMACIONES VIDA'
}